matrix:
  include:
    - {os: osx,  osx_image: xcode9.2,  language: objective-c}
    - {os: osx,  osx_image: xcode9.3,  language: objective-c}
    
    - {os: linux,  dist: trusty,  sudo: required,  language: generic,  env: 'SWIFT_VERSION=4.0'}
    - {os: linux,  dist: trusty,  sudo: required,  language: generic,  env: 'SWIFT_VERSION=4.1'}

install:
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    eval "$(curl -sL https://swiftenv.fuller.li/install.sh)";
  fi

script:
  - swift build
  - swift build -c release
  - swift test

after_success:
  eval "$(curl -sL https://raw.githubusercontent.com/florianreinhart/Geodesy/master/codecov.sh)"
