os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode9.3

env:
  - SWIFT_VERSION=4.1

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"

script:
  - swift build
  - swift build -c release
  - swift test

after_success:
  - eval "$(curl -sL https://raw.githubusercontent.com/florianreinhart/Geodesy/master/codecov.sh)"
