matrix:
  include:
    - {os: osx,  osx_image: xcode10.3,  language: objective-c}
    - {os: osx,  osx_image: xcode11.3,  language: objective-c}
    - {os: osx,  osx_image: xcode11.4,  language: objective-c}

    - {os: linux,  dist: trusty,  sudo: required,  language: generic,  env: 'SWIFT_VERSION=5.0'}
    - {os: linux,  dist: trusty,  sudo: required,  language: generic,  env: 'SWIFT_VERSION=5.1'}
    - {os: linux,  dist: trusty,  sudo: required,  language: generic,  env: 'SWIFT_VERSION=5.2'}

install:
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    eval "$(curl -sL https://swiftenv.fuller.li/install.sh)";
  fi

script:
  - swift build
  - swift build -c release
  - swift test

after_success:
  eval "$(curl -sL https://raw.githubusercontent.com/florianreinhart/Geodesy/master/codecov.sh)"
