name: test

on:
  push:
  pull_request:
  schedule:
    - cron: "0 12 * * 2"

jobs:
  macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Release build
      run: swift build -v -c release
    - name: Run tests
      run: swift test -v
  linux-5-7:
    runs-on: ubuntu-latest
    container:
      image: swift:5.7
    steps:
    - uses: actions/checkout@v2
    - name: Release build
      run: swift build -v -c release
    - name: Run tests
      run: swift test -v
  linux-5-6:
    runs-on: ubuntu-latest
    container:
      image: swift:5.6
    steps:
    - uses: actions/checkout@v2
    - name: Release build
      run: swift build -v -c release
    - name: Run tests
      run: swift test -v
  linux-5-5:
    runs-on: ubuntu-latest
    container:
      image: swift:5.5
    steps:
    - uses: actions/checkout@v2
    - name: Release build
      run: swift build -v -c release
    - name: Run tests
      run: swift test -v
