name: Swift

on:
  push:
  pull_request:
  schedule:
    - cron: "0 12 * * 2"

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v -c release
    - name: Run tests
      run: swift test -v
