name: test

on:
  push:
  pull_request:
  schedule:
    - cron: "0 12 * * 2"

jobs:
  macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Release build
      run: swift build -v -c release
    - name: Run tests
      run: swift test -v
  linux-5-2:
    runs-on: ubuntu-latest
    container:
      image: swift:5.2
    steps:
    - uses: actions/checkout@v2
    - name: Release build
      run: swift build -v -c release
    - name: Run tests
      run: swift test -v
  linux-5-1:
    runs-on: ubuntu-latest
    container:
      image: swift:5.1
    steps:
    - uses: actions/checkout@v2
    - name: Release build
      run: swift build -v -c release
    - name: Run tests
      run: swift test -v
  linux-5-0:
    runs-on: ubuntu-latest
    container:
      image: swift:5.0
    steps:
    - uses: actions/checkout@v2
    - name: Release build
      run: swift build -v -c release
    - name: Run tests
      run: swift test -v
